# Generated by Django 3.2.8 on 2021-10-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District_approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255, unique=True)),
                ('province', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funding_approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255, unique=True)),
                ('organization', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phonenumber', models.CharField(max_length=255, unique=True)),
                ('pic', models.BinaryField()),
                ('province', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('member_no', models.AutoField(primary_key=True, serialize=False)),
                ('overall_status', models.IntegerField(default=0)),
                ('stage1_status', models.IntegerField(default=0)),
                ('stage2_status', models.IntegerField(default=0)),
                ('district_approver', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('project_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('no_of_youth', models.IntegerField()),
                ('funding', models.CharField(max_length=255)),
                ('payback', models.CharField(max_length=255)),
                ('reference_no', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.member')),
            ],
        ),
    ]
