# Generated by Django 3.2.8 on 2021-10-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_member_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
