# Generated by Django 3.2.8 on 2021-10-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_auto_20211030_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stage1_approval_date',
            field=models.DateField(auto_now=True),
        ),
    ]
