# Generated by Django 3.2.8 on 2021-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_application_stage1_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
